org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true


## Environment Properties

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.248
neo_version_range=[21.1,)
loader_version_range=[4,)


## Mod Properties

mod_id=dldungeonsjbg
mod_name=Doomlike Dungeons
mod_license=MIT License
mod_version=2.2.0-MC1.21.1
mod_group_id=jaredbgreat.dldungeonsjbg
mod_authors=JaredBGreat, Xiroc
mod_description=A dungeon generator designed to create dungeons resembling levels from early FPS's like Doom, Heretic, and Hexen
